language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - cd ..
  - php dbcha/test/make-fpm-cfg.php $USER `pwd`/php-fpm.sock > ./php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm --fpm-config ./php-fpm.conf
  - ./dbcha/test/install-nginx.sh
  - php dbcha/test/make-nginx-cfg.php `pwd`/dbcha `pwd`/php-fpm.sock > ~/openresty/nginx/conf/nginx.conf
  - mv dbcha/test/testcfg.php dbcha/config.php
  - sudo ~/openresty/nginx/sbin/nginx
  - sleep 3
  - cd dbcha

script: phpunit